---
server:
    install: '1'
    packages: [git, vim, htop, sendmail, drush ,unzip, zip, g++, libssl-dev, apache2-utils]
    timezone: America/Chicago
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: tax, ip: 192.168.33.99, memory: '2024', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant/www
    servername: myApp.vb
mariadb:
    install: '1'
    root_password: taxnotes
    database: taxnotes
    user: taxnotes
    password: taxnotes
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-gd, php5-cli, php5-curl, php5-mcrypt, php5-mysql, php5-xdebug, php5-dev]
xdebug:
    install: '1'
composer:
    install: '1'

