---
server:
    install: '1'
    packages: [git, vim, sendmail, drush, unzip, zip, g++, libssl-dev, apache2-utils, openssl-blacklist, memcached]
    timezone: America/Chicago
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: drupal7, ip: 192.168.33.99, memory: '2048', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant/www
    servername: myApp.vb
mariadb:
    install: '1'
    root_password: drupal7
    database: drupal7
    user: drupal7
    password: drupal7
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-gd, php5-cli, php5-curl, php5-mcrypt, php5-mysql, php5-xdebug, php5-memcached, php5-memcache, php5-dev, php5-ldap, php5-gmp, php5-common, php-pear]

